CREATE DATABASE users;
USE users;

CREATE TABLE users (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR (120) NOT NULL,
	email VARCHAR (220) NOT NULL,
	country VARCHAR (120)
);

INSERT INTO users (id, name, email, country)
VALUES
	(1,'Vqsj Acin Vfuf','qlvqonfhvuv@gmail.com','Kdkl Fdkr');

INSERT INTO users (name, email, country)
VALUES
	('Vqsj Acin Vfuf','qlvqonfhvuv@gmail.com','Kdkl Fdkr'),
	('Kwqq Ofeu Hcak','imconcbdwsn@gmail.com','Ysmf Udgl'),
	('Dmty Jikz Eimz','avhiowfiwpp@gmail.com','Btze Zcqr'),
	('Egbl Aosl Dtsj','dmgkisahyqj@gmail.com','Cgmz Wgix'),
	('Gnld Zpxg Znaz','vodhanrcvtu@gmail.com','Awrv Eple'),
	('Vdnd Fpeh Vngl','dmrqkdjamve@gmail.com','Wsaz Ypsd'),
	('Ggkd Oyel Gpvn','ewrhltvrzyb@gmail.com','Vkem Bdtb'),
	('Ggzl Expc Jenn','shnbmcbhlwi@gmail.com','Ltdn Dwau'),
	('Drsu Fhhn Urof','xjcopfcqbyj@gmail.com','Rtzd Uyxl'),
	('Zssf Oeji Abhg','bktbyagebgk@gmail.com','Sgml Fuco'),
	('Tyme Vaek Hctn','wlourcuqbch@gmail.com','Ypzy Akjn'),
	('Vvua Ugty Qltf','gzpnqmdsoxn@gmail.com','Qkrf Pofz'),
	('Pjmj Diwo Zdtx','bjavkgpunuh@gmail.com','Hzdm Omwg'),
	('Aedo Sivd Uvcp','cjamnuuyuqs@gmail.com','Uwgj Qqtm'),
	('Sglr Cpsm Rjkg','yxmyazsimui@gmail.com','Bdhc Reez'),
	('Liyf Wimi Pjzy','bhgucdefkcr@gmail.com','Bcjb Troo'),
	('Yhgs Uhoi Jqxg','xclmuraqgpw@gmail.com','Rdzu Hkfh'),
	('Zpno Xvfb Phdc','gcnviayzgzc@gmail.com','Mfoa Arwn'),
	('Xhka Hpch Eelu','crgfgfmgprg@gmail.com','Fqex Wfbv'),
	('Egca Chys Mnup','kvcyhexgmrc@gmail.com','Ylzx Cbrn'),
	('Jqth Ufzo Cwoi','syjadkkxwmp@gmail.com','Kxlt Pnal'),
	('Ncif Kutz Koiy','bbxiokpyhgv@gmail.com','Hnej Rxzh'),
	('Rgkx Chyo Jqvk','uzhxsgedxcm@gmail.com','Ejfb Dgos'),
	('Gkve Cdsd Phzv','czhtewoqwcm@gmail.com','Cbug Xfvc'),
	('Evmg Vojw Otem','bjdepmrlrqn@gmail.com','Bzqf Sizg'),
	('Kkgf Jipe Pvvm','jmscwkbtiow@gmail.com','Stek Rfmr'),
	('Rsnd Lmvu Nizr','tutlvrzlvps@gmail.com','Mybj Wook'),
	('Zbob Cwpr Ikso','rvdqokflbib@gmail.com','Rxqp Umlo'),
	('Nqni Nosx Ruez','wohqshefjdt@gmail.com','Vemn Srka'),
	('Enfv Qqze Voro','yhqbomcvyyp@gmail.com','Iofu Uvrg'),
	('Hcyq Dchp Jbep','gxublmodybr@gmail.com','Dijy Eeay'),
	('Uvjb Ntzn Eayr','twspqzpaise@gmail.com','Uoex Hkkb'),
	('Mpwu Iift Kvpe','shddygxikmt@gmail.com','Scdj Nndz'),
	('Rear Evij Nmnl','mkcjewwhpea@gmail.com','Bqzf Beho'),
	('Twoa Lqzh Qejh','revvweuiplr@gmail.com','Bckr Xdzo'),
	('Vzhq Rcqq Kfbr','cpnntuovtgs@gmail.com','Xlil Wtqy'),
	('Mfel Mamq Mywt','cfuhsuflknb@gmail.com','Yrkw Wfnc'),
	('Ebmv Ysht Gcwf','wzomdugsavt@gmail.com','Ugeo Riea'),
	('Somr Dwqs Vxjj','ckwuuvmrvbj@gmail.com','Nreh Hgzo'),
	('Ihqd Kkfh Pzck','kmfnpuxglub@gmail.com','Usyt Yvdq'),
	('Gjjn Omdj Czep','hsxqhjmefoc@gmail.com','Ibll Lkys'),
	('Cqbv Mdtk Gltf','zktxmfmrrxv@gmail.com','Zocq Dmgc'),
	('Krwi Rwym Tcfc','umodgaxoegg@gmail.com','Sfmq Pfup'),
	('Xliw Wnjo Uebo','docaosqdlrb@gmail.com','Mfwj Nehp'),
	('Zone Pldf Ejhb','ygynbcmewlu@gmail.com','Ulcm Mmgr'),
	('Klzo Rwwg Qime','hcttezqjebc@gmail.com','Imrt Kxpu'),
	('Jxsq Rcgz Zgft','imzkqtwhxzi@gmail.com','Ktys Tewo'),
	('Aong Gqxn Aept','dnaoqmtxjta@gmail.com','Pgkm Bbeu'),
	('Lgxk Tnjq Vzzz','bdasbvfesyz@gmail.com','Tmth Csgj'),
	('Gbtm Zaxk Uyvf','oewkqdesojj@gmail.com','Yovw Ykfe'),
	('Xgaw Pngl Qhzf','ikyoazkldge@gmail.com','Eulz Avjn'),
	('Krcr Rizu Xnea','memjybxbjjx@gmail.com','Xcmf Iylz'),
	('Rkhz Vppd Vpqu','sfbxnwgjqgs@gmail.com','Uvfd Qmtg'),
	('Lvjv Rlvw Sxsw','ztotlbicgcu@gmail.com','Sfjx Kuci'),
	('Jrro Lgwb Rbnc','angctfcnrmp@gmail.com','Fvrt Axuf'),
	('Qtuz Pybx Hjao','tnjggtlknel@gmail.com','Giyu Iixs'),
	('Drly Xazs Cspk','bmwnzqcfder@gmail.com','Kqhz Ixyy'),
	('Bysf Vssb Yuoi','oqpdxozfshk@gmail.com','Rkxi Qpcb'),
	('Xuup Bfop Frhv','hiodrkwpowf@gmail.com','Vbak Rikx'),
	('Ymgh Oxmh Yhrx','cpnxutocbxu@gmail.com','Vdge Thcc'),
	('Ookf Zhpr Ihbl','mcwlvhwyrcl@gmail.com','Hnti Cggl'),
	('Egwt Cmhl Bwxz','fddytgtwtqi@gmail.com','Sydh Pnvs'),
	('Ptop Ogem Bsdu','thxiiyvufgj@gmail.com','Rzye Uddq'),
	('Lcyg Jfjd Khus','pjcugzopwah@gmail.com','Pxdx Okbd'),
	('Dwhc Cyxp Hxyp','oemeegbctxs@gmail.com','Lepr Cfkf'),
	('Tlok Glja Kzbh','huexdhtfkuk@gmail.com','Mses Jxlb'),
	('Dclp Rpbs Anxa','iykkdxgwqkr@gmail.com','Vtbm Honq'),
	('Kwjl Oukd Erfq','xcuzafuzjhi@gmail.com','Dwag Eliq'),
	('Tceh Tdbl Cmmk','wzsfhiqtuky@gmail.com','Wrhv Zxgy'),
	('Ydgy Mwdw Sawu','xsralndshdt@gmail.com','Epsk Jcme'),
	('Lqgn Mpeh Bsld','swvptovuxsr@gmail.com','Iont Hrxl'),
	('Mcyb Wjib Ufuz','oypzehpsjot@gmail.com','Xpdi Mwqd'),
	('Wame Ztwc Hyej','ibplmomlmgg@gmail.com','Oday Atxc'),
	('Isma Nzzr Gryj','vcfwkpqlfon@gmail.com','Odvt Arhv'),
	('Hvdb Tmvc Qgez','mpgnsevjxau@gmail.com','Siqo Guwi'),
	('Uema Kpum Pvhw','zygmtldfraw@gmail.com','Fiic Ekzg'),
	('Kjku Jnkt Erob','djdhjsujblh@gmail.com','Lczf Udis'),
	('Zxlb Mchf Abqp','upvncbiqrwr@gmail.com','Oepz Wsxb'),
	('Guan Mzhg Rfll','rqoiqckooqa@gmail.com','Yxss Ypcp'),
	('Alll Lgxa Fpyg','lvzeppnbuoe@gmail.com','Jprf Epgm'),
	('Jkth Ooyd Rhgz','dysosparakn@gmail.com','Fnji Syep'),
	('Msmw Nqyn Zhzl','mzobrvozqmq@gmail.com','Zeuh Vxpv'),
	('Lwaj Zchn Jeps','lnnjkkfexwv@gmail.com','Pjwx Mexq'),
	('Iujc Bvou Tqud','uwucrubhxxg@gmail.com','Nypa Kkxy'),
	('Ihsz Vdus Vkju','nqmqixxrmzr@gmail.com','Zgus Pvya'),
	('Qhet Lzan Kfbb','jpibzdirxhc@gmail.com','Rmoa Wvrw'),
	('Owkg Lost Rqbk','vciytxbhxan@gmail.com','Gtdg Pdoo'),
	('Wefl Lzyu Horz','zrfrcegdmnu@gmail.com','Jqzd Rptf'),
	('Fyhx Egva Vhvl','ayycqelfbor@gmail.com','Sqkm Tykl'),
	('Kpuh Cbyx Lndn','xghkcfirihk@gmail.com','Tyob Ylne'),
	('Rpkf Qcbq Xzum','atusnvpphkl@gmail.com','Sprs Reuw'),
	('Bnhn Weqi Soje','ustdechtnte@gmail.com','Ilik Vroz'),
	('Ntow Esxe Ofnf','iexhwwjtsei@gmail.com','Qyap Dibs'),
	('Kfqo Kcij Hrlr','gghnfraoiqr@gmail.com','Xpmi Qkak'),
	('Zjxe Dfgo Inyq','lqqgnjnjgxn@gmail.com','Nsof Iqdq'),
	('Wjep Ihfj Rlyi','urjwzdpadkh@gmail.com','Qaog Mnrt'),
	('Nlda Vqze Szeu','yhdcgqekihm@gmail.com','Aajq Wbmq'),
	('Lwyo Oklg Oyqc','qlcfsrhbydn@gmail.com','Llkv Nvor'),
	('Khbe Ymhg Nrlo','uzqujvitedc@gmail.com','Skip Bkak'),
	('Micf Ugqz Sdus','ejucsvjskjk@gmail.com','Vejh Cxfq'),
	('Zbjq Vmvt Fzld','hsueztkyqvm@gmail.com','Clwb Hmff'),
	('Mxog Svss Ufno','snhlboxhffu@gmail.com','Ixcf Avbt'),
	('Jfkb Yeje Gisi','rbrzziazqzo@gmail.com','Ogix Ljeu'),
	('Fxfw Vwkz Fdfy','nvcrubyzgwm@gmail.com','Ddfy Uzll'),
	('Xiyn Dglk Uqri','drcyjmbygzs@gmail.com','Lhao Oidk'),
	('Opaj Lkpg Fmie','xvwfiyoxfxu@gmail.com','Ykqs Nyey'),
	('Ksei Garw Legh','aecequqhllv@gmail.com','Ncqt Rdfv'),
	('Rval Umws Wezy','brfrzclafkm@gmail.com','Utri Snce'),
	('Gonv Qyqk Opuf','agklbfkoiiy@gmail.com','Cjxz Bwim'),
	('Jbrb Khij Mvvh','rcnnynrmxkr@gmail.com','Zkda Glem'),
	('Jzat Zdsa Cazk','zhygumvyfbr@gmail.com','Uask Rewv'),
	('Awjs Odfl Hzsl','elshhkrkbag@gmail.com','Rbwu Rmee'),
	('Bpdn Ifgs Agst','prtidisavjb@gmail.com','Tfld Zzvp'),
	('Mjnn Eukn Lfvv','nofhbrbervw@gmail.com','Fwbz Webc'),
	('Vrtz Tnvq Kfns','vobmjsahrbd@gmail.com','Gzlv Jjrc'),
	('Xgnu Paga Jats','penzmidwtkq@gmail.com','Ykpn Qrfe'),
	('Hqvt Iita Oaxr','gtczfcfjhsh@gmail.com','Mzlh Hjwg'),
	('Gczh Qnxs Nief','wpnqaonnlca@gmail.com','Hmlz Tdap'),
	('Dldc Hpeu Fnnm','pqlmnpgunxu@gmail.com','Aymr Ljkn'),
	('Ubte Widf Ywbb','mcqnlbyskjh@gmail.com','Fvlh Qgft'),
	('Vwna Dwbs Eenn','vtvxmnmkkoz@gmail.com','Ibyg Vegt'),
	('Xvck Qzwi Rxzp','mxlfbkhusjk@gmail.com','Hcni Bsjg'),
	('Daeb Tpie Reuk','gwddfdbaqag@gmail.com','Uoci Qifd'),
	('Gezu Tjce Wbot','zsbkerwvjkc@gmail.com','Btwc Zmsc'),
	('Xkyv Zjzc Npdx','pbqpzfeanjh@gmail.com','Bdqu Czmv'),
	('Cxzw Idmq Aetk','lcsivkpbsaj@gmail.com','Yspq Qdxo'),
	('Lypx Cukn Hxko','iihcbpncpxd@gmail.com','Zoho Najq'),
	('Maeu Dtdr Jmrm','wreeyuonqgh@gmail.com','Jcxl Rkzd'),
	('Phsr Fzlw Wmzy','zpdckqxzjbw@gmail.com','Dhbn Bcmy'),
	('Zfit Yrdf Uvah','yeycrzvpyja@gmail.com','Ugvj Ibwg'),
	('Miuw Qloc Adaf','ifivehiaxvl@gmail.com','Mpni Acyt'),
	('Xkmd Nzwc Awsz','cvuweylspgu@gmail.com','Hosg Mddg'),
	('Snic Mgpa Wluv','kdvpqmzviku@gmail.com','Ogxt Nhev'),
	('Hfia Wxex Pcez','oifrcpbnpzi@gmail.com','Jlvl Mkkl'),
	('Hvfi Xvrf Fivo','kmrzsejbhvz@gmail.com','Eqqz Pfpq'),
	('Nafs Kdff Mjoz','rznwbwmadsg@gmail.com','Irpm Qabp'),
	('Wfpk Ixmf Oauv','zzwmgjilezf@gmail.com','Ymzg Xnff'),
	('Rjlx Yorr Dzge','ourovpkesen@gmail.com','Epgh Sxmb'),
	('Fezl Qddy Xjir','gwwymoempdm@gmail.com','Stga Ohem'),
	('Qpwu Mjnd Svxq','iynjvpccfit@gmail.com','Bxar Racj'),
	('Zmng Txnt Wpou','zaczymzjtqd@gmail.com','Tovt Vyxj'),
	('Nrim Bqnz Kveg','ffojyfwhlrm@gmail.com','Mjut Cjow'),
	('Xmvl Mypu Kbry','qivzviywbwt@gmail.com','Hnla Gpfu'),
	('Elef Ujjb Byxl','kwgktwhrwbg@gmail.com','Iwwt Pxsp'),
	('Dhfs Iljb Gxvk','xlkkwmfqngf@gmail.com','Wjhc Cwfn'),
	('Yzba Xkyr Oiyk','vblturetfgz@gmail.com','Ivcg Xuqi'),
	('Lsnj Zdhj Pjep','olcyoosyftq@gmail.com','Cpgh Fmnc'),
	('Yuha Bbze Qqkb','lxvoqzuzpfh@gmail.com','Qyyb Cpgt'),
	('Wgxp Wbuq Engq','ppdhryvnhcj@gmail.com','Lciz Orrb'),
	('Dtrp Lyid Wypb','emgsdlcmteu@gmail.com','Fkmj Kvjj');


